@startuml
interface ChristmasTree {
 +decorate(): String
}
class ChristmasTreeImpl implements ChristmasTree {
  + decorate(): String
}

abstract class TreeDecorator  implements ChristmasTree{
 +decorate(): String
}

class BubbleLights extends TreeDecorator{
 ChristmasTree tree
 ..
 +decorate: String
 -decorateWithBubbleLights(): String

}

class Garland extends TreeDecorator{
 ChristmasTree tree
 ..
 +decorate: String
 -decorateWithGarland(): String

}

class Tinsel extends TreeDecorator{
 ChristmasTree tree
 ..
 +decorate: String
 -decorateWithTinsel(): String
}

class TreeTopper extends TreeDecorator{
 ChristmasTree tree
 ..
 +decorate: String
 -decorateWithTreeTopper(): String

}
@enduml